# Docs for Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - testing-3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies, build, test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./server

      - name: Zip project
        run: zip -r release.zip .
        working-directory: ./server

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./server/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download zip artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip backend
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BF2FDCF3FA3A430A95FEEBA4D61CA016 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_632813F1E5CA42EFA26F9D0BE4F19BA7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_479CEAEEEF4840CDA38D6B04D0D6033E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Trendikala-testing'
          slot-name: 'Production'
          package: .
